spring:
  datasource:
    hikari:
      maximum-pool-size: 50
#      minimum-idle: 5
#      idle-timeout : 300000
#      max-lifetime : 1800000
#      connection-timeout: 20000

    url: jdbc:postgresql://pgdbs.postgres.database.azure.com:5432/postgres
    username: expowhiz
    password: Demo@admin

#    Student
#    url: jdbc:postgresql://irctc.postgres.database.azure.com:5432/postgres


#    LOCAL
#    url: jdbc:postgresql://localhost:5432/irctc_db
#    username: postgres
#    password: Irctc_2.0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: b5c3d8b1e1a7324d99e87a4ebf03fdd8a6d3c987ee5a8f2c51fdb6b89e7fd42a
  expiration-ms: 2592000000 # Token validity: 30 days (1 month)
discord:
  webhook:
    url: "https://discord.com/api/webhooks/1357252242310434866/jfhcNhULG-B64HB4S85LqXB4pscelqhVNug6JAlBGSYRWYNkxKZzGrvPuLcKh6tAkSoP"

razorpay:
  keyId: rzp_test_fCAXi9H2JlDUje
  keySecret: MU6QpUu4z558Lq8eFr0j4DOQ

user:
  password:
    expiry-days: 90

