package com.irctc2.user.dto;

import lombok.Data;

@Data
public class ChangePasswordRequest {

    private String oldPassword; // User's current password
    private String newPassword; // User's desired new password

    // No-args constructor, getters, and setters are automatically generated by Lombok
}
